apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-app
  labels:
    app: gradio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio
  template:
    metadata:
      labels:
        app: gradio
    spec:
      containers:
      - name: gradio-container
        image: intelytica/diabetes:v1
        ports:
        - containerPort: 7860
